packages:
  - build-essential
  - libssl-dev
  - llvm
  - python3-pip
  - python-is-python3
  - vim
  - less

brew:
  taps:
    # - hashicorp/tap
    - aws/tap
    - carlocab/personal
    - homebrew/bundle
    - homebrew/cask
    - homebrew/cask-fonts
    - homebrew/core
  casks:
    - alacritty
    - alt-tab
    - aws-vault
    - font-fira-code-nerd-font
    - hiddenbar
    - rectangle
    - tunnelblick
  packages:
    common:
      - asciinema
      - asdf
      - autoconf
      - automake
      - azure-cli
      - bat
      - coreutils
      - direnv
      - dos2unix
      - dust
      - exa
      - fd
      - fzf
      - gh
      - ghq
      - git-delta
      - hadolint
      - highlight
      - jq
      - jsonnet
      - kustomize
      - lazygit
      - lua-language-server
      - p7zip
      - packer
      - pkg-config
      - pre-commit
      - python-yq
      - ripgrep
      - sponge
      - terraform-docs
      - tflint
      - tfsec
      - tldr
      - tre-command
      - tree
      - tree-sitter
      - yamllint
      - zoxide
    darwin:
      - carlocab/personal/unrar
      - ffmpeg
      - gawk
      - gnu-getopt
      - gnu-sed
      - watch
      - wget
      - xz
    linux: []
  packages_from_source:
    - duf

dotfiles:
  repo: 'https://github.com/shmileee/dotfiles'
  branch: 'master'

neovim:
  build_from_source: false
  directory: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"
  build_dependencies:
    - autoconf
    - automake
    - cmake
    - curl
    - doxygen
    - g++
    - gettext
    - libtool
    - libtool-bin
    - ninja-build
    - pkg-config
    - unzip

asdf_version: "v0.9.0"
asdf_plugins:
  - name: "python"
    repository: "https://github.com/danhper/asdf-python"
    versions:
      - 3.10.1
    delete_versions: []
    global: system

  - name: "golang"
    repository: "https://github.com/kennyp/asdf-golang"
    versions:
      - 1.18
    delete_versions: []
    global: system

  - name: "ruby"
    repository: "https://github.com/asdf-vm/asdf-ruby"
    versions:
      - 3.0.3
    delete_versions: []
    global: system

  - name: "nodejs"
    repository: "https://github.com/asdf-vm/asdf-nodejs"
    versions:
      - 17.7.2
    delete_versions: []
    global: system

  - name: "terraform"
    repository: "https://github.com/asdf-community/asdf-hashicorp"
    versions:
      - 1.1.7
    delete_versions: []
    global: 1.1.7

  - name: "terraform-ls"
    repository: "https://github.com/shihanng/asdf-terraform-ls"
    versions:
      - 0.26.0
    delete_versions: []
    global: 0.26.0

  - name: "kubectl"
    repository: "https://github.com/asdf-community/asdf-kubectl"
    versions:
      - 1.23.0
    delete_versions: []
    global: 1.23.0

  - name: "helm"
    repository: "https://github.com/Antiarchitect/asdf-helm"
    versions:
      - 3.8.1
    delete_versions: []
    global: 3.8.1

golang:
  path: '{{ ansible_user_dir }}/.go'
  packages:
    - golang.org/x/tools/cmd/goimports@latest
    - golang.org/x/tools/gopls@latest

nodejs:
  packages:
    - yarn
