- name: Include SDKMAN Role
  include_role:
    name: Comcast.sdkman
  vars:
    sdkman_user: aaroncoville
    sdkman_auto_answer: true
    sdkman_update: true
    sdkman_install_packages:
      - { candidate: java, version: 8.0.322-zulu }
      - { candidate: gradle, version: 7.4.1 }
    sdkman_flush_caches_before:
      - temp
    sdkman_flush_caches_after:
      - archives
      - broadcast
      - candidates
      - temp
    sdkman_offline_mode: false
    sdkman_update_alternatives:
      - candidate: java
        name: java
        link: /usr/bin/java
      - candidate: java
        name: javac
        link: /usr/bin/javac
  tags:
    - java
    - sdkman
- name: Ensure SDKMAN is in PATH
  shell: source "$HOME/.sdkman/bin/sdkman-init.sh"
  tags:
    - java
    - sdkman
